ground_truth = [
    ("The cat is sleeping on the couch.", "Animal Behavior"),
    ("She enjoyed reading the new science fiction book.", "Science and Technology"),
    ("The economy is expected to grow by 2% this year.", "Business and Economy"),
    ("He loves playing basketball every weekend.", "Sports and Recreation"),
    ("A thunderstorm is expected in the afternoon.", "Weather and Climate"),
    ("They adopted a stray dog from the shelter.", "Animal Behavior"),
    ("The recipe calls for fresh basil and garlic.", "Food and Cooking"),
    ("The new movie was a huge box office success.", "Entertainment and Media"),
    ("He forgot to submit the assignment before the deadline.", "Education and Learning"),
    ("The scientist conducted an experiment on plant growth.", "Science and Technology"),
    ("The company announced a new smartphone model.", "Science and Technology"),
    ("She went for a hike in the mountains.", "Travel and Adventure"),
    ("The baby started walking at just nine months old.", "Personal Development"),
    ("They traveled to France for their honeymoon.", "Travel and Adventure"),
    ("The teacher explained the concept of gravity.", "Education and Learning"),
    ("He invested in renewable energy stocks.", "Business and Economy"),
    ("The car broke down in the middle of the highway.", "Community and Charity"),
    ("She painted a beautiful landscape of the ocean.", "Art and Creativity"),
    ("The city council is planning to build a new park.", "Community and Charity"),
    ("The singer performed live in front of thousands of fans.", "Entertainment and Media"),
    ("He trained for months to prepare for the marathon.", "Sports and Recreation"),
    ("The new policy aims to reduce air pollution.", "Weather and Climate"),
    ("She baked a cake for her friend's birthday party.", "Food and Cooking"),
    ("The professor gave an insightful lecture on climate change.", "Environment and Nature"),
    ("They planted trees to celebrate Earth Day.", "Weather and Climate"),
    ("The child built a sandcastle at the beach.", "Personal Development"),
    ("The government is considering a tax cut for small businesses.", "Business and Economy"),
    ("He joined a photography club to improve his skills.", "Art and Creativity"),
    ("The artist held an exhibition to showcase her work.", "Art and Creativity"),
    ("She found a wallet on the street and returned it to its owner.", "Community and Charity"),
    ("The robot can clean the entire house automatically.", "Science and Technology"),
    ("The actor won an award for his outstanding performance.", "Entertainment and Media"),
    ("The school organized a science fair for the students.", "Education and Learning"),
    ("She started learning Japanese in her free time.", "Personal Development"),
    ("The bookshop is offering a discount on bestsellers.", "Education and Learning"),
    ("The athletes trained hard for the upcoming competition.", "Sports and Recreation"),
    ("The solar panels generate enough power for the entire house.", "Science and Technology"),
    ("He loves listening to classical music in the evening.", "Art and Creativity"),
    ("The astronaut shared stunning photos of Earth from space.", "Art and Creativity"),
    ("The team developed an app to track fitness goals.", "Sports and Recreation"),
    ("She spends her weekends volunteering at the animal shelter.", "Community and Charity"),
    ("The film received critical acclaim for its screenplay.", "Entertainment and Media"),
    ("The children were excited to see the fireworks display.", "Entertainment and Media"),
    ("He learned to play the piano during the lockdown.", "Art and Creativity"),
    ("The farmer harvested a bumper crop this season.", "Food and Cooking"),
    ("The library offers free workshops on creative writing.", "Art and Creativity"),
    ("She designed a website for her small business.", "Business and Economy"),
    ("The hiking trail is surrounded by breathtaking views.", "Travel and Adventure"),
    ("The government launched a campaign to promote vaccinations.", "Travel and Adventure"),
    ("The train was delayed due to technical issues.", "Travel and Adventure"),
    ("He solved the puzzle in record time.", "Personal Development"),
    ("She enjoyed the concert featuring her favorite band.", "Entertainment and Media"),
    ("The scientist discovered a new species of butterfly.", "Animal Behavior"),
    ("The bakery sells freshly baked bread every morning.", "Food and Cooking"),
    ("He narrated a fascinating story about his travels.", "Travel and Adventure"),
    ("The festival celebrated the rich culture of the community.", "Community and Charity"),
    ("She donated her old clothes to a charitable organization.", "Community and Charity"),
    ("The chef prepared a delicious Italian meal.", "Food and Cooking"),
    ("The workshop focused on stress management techniques.", "Education and Learning"),
    ("The garden is filled with vibrant flowers in spring.", "Environment and Nature"),
    ("The research team published a paper on artificial intelligence.", "Science and Technology"),
    ("The dog learned new tricks in just a few weeks.", "Animal Behavior"),
    ("She renovated her kitchen with modern appliances.", "Food and Cooking"),
    ("The fire department quickly extinguished the blaze.", "Community and Charity"),
    ("He plans to start a podcast about technology trends.", "Science and Technology"),
    ("The kids enjoyed a fun day at the amusement park.", "Entertainment and Media"),
    ("The organization raised funds for disaster relief efforts.", "Weather and Climate"),
    ("She joined a yoga class to stay fit and relaxed.", "Health and Fitness"),
    ("The author signed copies of his latest book.", "Art and Creativity"),
    ("The fisherman caught a massive tuna in the ocean.", "Environment and Nature"),
    ("The company is working on a self-driving car prototype.", "Innovation and Invention"),
    ("She presented her artwork at the annual art fair.", "Art and Creativity"),
    ("The students organized a clean-up drive in their neighborhood.", "Community and Charity"),
    ("The plane landed safely despite the bad weather.", "Weather and Climate"),
    ("The team celebrated their victory in the championship.", "Sports and Recreation"),
    ("She adopted a plant-based diet for health reasons.", "Food and Cooking"),
    ("The city experienced record-breaking temperatures this summer.", "Weather and Climate"),
    ("He helped his grandmother plant flowers in her garden.", "Environment and Nature"),
    ("The software update fixed several bugs in the system.", "Science and Technology"),
    ("She crafted handmade jewelry as a hobby.", "Art and Creativity"),
    ("The company offered internships to university students.", "Education and Learning"),
    ("The new park includes a playground and walking trails.", "Environment and Nature"),
    ("He cycled through the countryside during his vacation.", "Travel and Adventure"),
    ("The museum displayed artifacts from ancient civilizations.", "Art and Creativity"),
    ("The student excelled in math and science subjects.", "Education and Learning"),
    ("The festival featured live music and dance performances.", "Entertainment and Media"),
    ("She shared her favorite recipes on a food blog.", "Food and Cooking"),
    ("The car manufacturer unveiled an electric vehicle.", "Science and Technology"),
    ("The beach was crowded with tourists during the holiday season.", "Travel and Adventure"),
    ("The community center hosts free fitness classes.", "Community and Charity"),
    ("The engineer designed a bridge over the river.", "Innovation and Invention"),
    ("She adopted a rescue cat named Whiskers.", "Animal Behavior"),
    ("The charity organized a marathon to support cancer research.", "Community and Charity"),
    ("The photographer captured stunning images of wildlife.", "Animal Behavior"),
    ("The startup developed an innovative water purification system.", "Innovation and Invention"),
    ("The band released their new album online.", "Entertainment and Media"),
    ("She climbed Mount Everest as part of an expedition.", "Travel and Adventure"),
    ("The school held a talent show to showcase students' skills.", "Education and Learning"),
    ("The zoo welcomed a baby elephant born last week.", "Animal Behavior"),
    ("The app allows users to book tickets for events easily.", "Science and Technology"),
]
